# Allow the wheel group to drive MSI EC controls from user-level Waybar scripts.
z /sys/devices/platform/msi-ec/leds/platform::mute/brightness 0664 root wheel -
z /sys/devices/platform/msi-ec/leds/platform::micmute/brightness 0664 root wheel -
z /sys/devices/platform/msi-ec/webcam 0664 root wheel -
z /sys/devices/platform/msi-ec/webcam_block 0664 root wheel -
