################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = eDP-1,                                         1920x1080@240,  0x0,        1.00, transform, 0
monitor = desc:LG Electronics 19EN33 307NDZJJW461,       1366x768@77,    auto-up,    0.67
monitor = desc:RGT 0x1352 0x01010101,                    1366x768@77,    auto-up,    0.67
monitor = HEADLESS-1,                                    1920x1080@60,   auto-right, 1

#monitorv2 {
#    output = eDP-1
#    mode = 1920x1080@60
#    position = 0x0
#    scale = 1
#}

#monitorv2 {
#   output = HDMI-A-1
#   mode = 1920x1080@100
#	mode = 1366x768@60
#	mode = 1366x768@77
#   position = 1920x-450
#   scale = 0.67
#}
