###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$fileManager = thunar
$menu = hyprlauncher

$wallpaper = /home/remenod/.local/share/backgrounds/2025-11-29-00-12-37-wallpaper.png
