# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0

windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}

windowrule {
     name = no-gaps-wtv1
     match:float = false
     match:workspace = w[tv1]

     border_size = 0
     rounding = 0
}

#windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
#}

windowrule = match:class alacritty-popup-menu, float on, center on, size 400 300, workspace special
windowrule = match:class alacritty-fastfetch, float on, center on, size 900 500, workspace special
windowrule = match:class alacritty-connect-menu, float on, center on, size 950 600, workspace special

windowrule = match:class steam, float on
windowrule = match:class steam, match:title Steam, tile on
