# Hyprland config entrypoint.
source = ~/.config/hypr/conf.d/00-core.conf
source = ~/.config/hypr/conf.d/10-monitors.conf
source = ~/.config/hypr/conf.d/20-programs.conf
source = ~/.config/hypr/conf.d/30-autostart.conf
source = ~/.config/hypr/conf.d/40-environment.conf
source = ~/.config/hypr/conf.d/50-permissions.conf
source = ~/.config/hypr/conf.d/60-appearance.conf
source = ~/.config/hypr/conf.d/65-workspace-rules.conf
source = ~/.config/hypr/conf.d/70-layouts.conf
source = ~/.config/hypr/conf.d/80-input.conf
source = ~/.config/hypr/conf.d/90-binds.conf
source = ~/.config/hypr/conf.d/95-windowrules.conf
